---
log:
  level: {{ env "LOG_LEVEL" }}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
    swarmMode: true
  file:
    filename: /etc/traefik/file-provider.yml

api:
  dashboard: {{ env "DASHBOARD_ENABLED" }}
  debug: false

entrypoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure
  web-secure:
    address: ":443"
  gitea-ssh:
    address: ":2222"
  foodsoft-smtp:
    address: ":2525"
  {{ if eq (env "SMTP_ENABLED") "1" }}
  smtp-submission:
    address: ":587"
  {{ end }}

ping:
  entryPoint: web

certificatesResolvers:
  staging:
    acme:
      email: {{ env "LETS_ENCRYPT_EMAIL" }}
      storage: /etc/letsencrypt/staging-acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
  production:
    acme:
      email: {{ env "LETS_ENCRYPT_EMAIL" }}
      storage: /etc/letsencrypt/production-acme.json
      httpChallenge:
        entryPoint: web
