---
log:
  level: INFO

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
    swarmMode: true
  file:
    filename: /etc/traefik/file-provider.yml

api:
  dashboard: false
  debug: false

entrypoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure
  web-secure:
    address: ":443"
  gitea-ssh:
    address: ":2222"

certificatesResolvers:
  staging:
    acme:
      email: helo@autonomic.zone
      storage: /etc/letsencrypt/staging-acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
  production:
    acme:
      email: helo@autonomic.zone
      storage: /etc/letsencrypt/production-acme.json
      httpChallenge:
        entryPoint: web
